name: "Close Invalid PRs"
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  close_invalid_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Close Invalid PR
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const pr = context.payload.pull_request;
          if (pr.base.ref === 'main' && pr.head.ref !== 'devel') {
            github.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Sorry, we only accept PRs to master from the devel branch. This PR will be closed.'
            });
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              state: 'closed'
            });
          }
